package com.hydroponics.management.system.entities.enums;

public enum NotificationType {

	EXPIRATION_DATE_ERROR,
	INVALID_TEMPERATURE_ERROR,
	INVALID_WATER_pH_ERROR,
	INVALID_HUMIDITY_ERROR,
	INVALID_LIGHT_DURATION_ERROR,
	INVALID_MINERAL_ERROR,
	SUCCESS_ENVIRONMENT_CREATION,
	SUCCESS_FULL_PAYMENT,
	SUCCESS_PARTIAL_PAYMENT,
	UNPAID_PAYMENT,
	FAILED_FULL_PAYMENT,
	FAILED_PARTIAL_PAYMENT,
	SUCCESS_USER_REGISTRATION
}
